#index:
#    path: /
#    controller: App\Controller\DefaultController::index
get_orders:
  path: /order/getorders
  controller: App\Controller\OrderController::getOrders
  methods: GET|POST

get_order:
  path: /order/getorder
  controller: App\Controller\OrderController::getOrder
  methods: GET|POST

add_order:
  path: /order/addorder
  controller: App\Controller\OrderController::addOrder
  methods: POST
